app:
    type: rest
    resource: "@AppBundle/Controller/"
    prefix: /api

tasks:
    type: rest
    resource: AppBundle\Controller\TaskController

users:
    type: rest
    resource: AppBundle\Controller\UserController

api_login_check:
    path: /api/login_check
